// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkMCFWV119xRglmufeAFt8fpa6egPNW4U',
    appId: '1:292478235843:web:db6edacade5c0bbd4a9e76',
    messagingSenderId: '292478235843',
    projectId: 'citi-smart-c5927',
    authDomain: 'citi-smart-c5927.firebaseapp.com',
    storageBucket: 'citi-smart-c5927.appspot.com',
    measurementId: 'G-73VL8GJMQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE34RD-QOhcJVrI3HmXZ6sLefRtUlEq60',
    appId: '1:292478235843:android:4960c6ac3b61dfa24a9e76',
    messagingSenderId: '292478235843',
    projectId: 'citi-smart-c5927',
    storageBucket: 'citi-smart-c5927.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA43tLIb1vp_PaJDiTwf8o1lX8dz3P-pFk',
    appId: '1:292478235843:ios:be3e355a309b6e144a9e76',
    messagingSenderId: '292478235843',
    projectId: 'citi-smart-c5927',
    storageBucket: 'citi-smart-c5927.appspot.com',
    iosBundleId: 'com.example.citiSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA43tLIb1vp_PaJDiTwf8o1lX8dz3P-pFk',
    appId: '1:292478235843:ios:be3e355a309b6e144a9e76',
    messagingSenderId: '292478235843',
    projectId: 'citi-smart-c5927',
    storageBucket: 'citi-smart-c5927.appspot.com',
    iosBundleId: 'com.example.citiSmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkMCFWV119xRglmufeAFt8fpa6egPNW4U',
    appId: '1:292478235843:web:b8448b73d174aa9a4a9e76',
    messagingSenderId: '292478235843',
    projectId: 'citi-smart-c5927',
    authDomain: 'citi-smart-c5927.firebaseapp.com',
    storageBucket: 'citi-smart-c5927.appspot.com',
    measurementId: 'G-Q4STZFV2NE',
  );
}
